#-------------------------------
# General Site Settings
title: Michael Willingham
logo: '/images/site-logo.png'
description: Michael Willingham - Musings on tech, sports, and faith
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Michael Willingham
  avatar: '/images/michael-headshot.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Michael Willingham
  description: Musings on tech, sports, and faith
  image: '/images/index-header.jpeg'


#-------------------------------
# Contact Settings
contact:
  email: michaelhwillingham@protonmail.com # Add your email for contact form
  description: # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Social icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-github", link: "https://github.com/michaelhwillingham"}
- {icon: "ion-logo-linkedin", link: "https://linkedin.com/in/michael-h-willingham"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: michaelhwillingham # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed